

--Weather Observation Station 5
SELECT TOP 1 CITY, LEN(CITY) FROM STATION ORDER BY LEN(CITY), CITY;
SELECT TOP 1 CITY, LEN(CITY) FROM STATION ORDER BY LEN(CITY) DESC, CITY;

--Higher Than 75 Marks
SELECT Name FROM Students WHERE Marks > 75 ORDER BY RIGHT(Name, 3), ID

--Weather Observation Station 6
SELECT COUNT(CITY) - COUNT(DISTINCT CITY) FROM STATION;

--Weather Observation Station 4
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE '[AEIOU]%' ORDER BY CITY;

--Weather Observation Station 9
SELECT DISTINCT CITY FROM STATION WHERE CITY NOT LIKE '[AEIOU]%' ORDER BY CITY;
